In [2]:
import torch

In [3]:
list_a = [1, 2, 3, 4]
tensor_a = torch.tensor(list_a)

In [4]:
# Display the tensor device
print(tensor_a.device)

# Display the tensor data type
print(tensor_a.dtype)

cpu
torch.int64


In [5]:
list_b = [5, 6, 7, 8]
tensor_b = torch.tensor(list_b)


In [6]:
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [7]:
tensor_a - tensor_b

tensor([-4, -4, -4, -4])

In [8]:
tensor_a * tensor_b


tensor([ 5, 12, 21, 32])

In [9]:
tensor_a / tensor_b

tensor([0.2000, 0.3333, 0.4286, 0.5000])

## Reshaping

In [11]:
labels = torch.tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
reshaped_labels = labels.view(-1, 1)
print(reshaped_labels.shape)  # Output: torch.Size([any_number, 1])
print(reshaped_labels)

tensor([[0],
        [1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])


In [25]:
labels = torch.tensor([[0],
        [1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])

reshaped_labels = labels.view(2, -1, 1)
print(reshaped_labels.shape)  # Output: torch.Size([2, any_number, 1])
print(reshaped_labels)

torch.Size([2, 5, 1])
tensor([[[0],
         [1],
         [2],
         [3],
         [4]],

        [[5],
         [6],
         [7],
         [8],
         [9]]])
